name: Automated Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Run Test 1
        run: |
          python find_lowest_number.py test_data/test1_input.txt output1.txt
          diff output1.txt test_data/test1_expected.txt

      - name: Run Test 2
        run: |
          python find_lowest_number.py test_data/test2_input.txt output2.txt
          diff output2.txt test_data/test2_expected.txt

      - name: Run Test 3
        run: |
          python find_lowest_number.py test_data/test3_input.txt output3.txt
          diff output3.txt test_data/test3_expected.txt
